trigger:
- acceptatie

resources:
  repositories:
    - repository: templates
      type: git
      name: MSS-Azure
      ref: master

extends:
  template: MSS-Azure-CoronaMelder-Pipelines/webapp-build-deploy.yml@templates
  parameters:
    environment: 'covid19-azure-acceptance'
    # ============================================
    # parameters hieronder zijn alleen voor testen
    #azureSubscriptionPrimary: 'mss-vws-acc-cicd'
    #webAppNamePrimary: 'vwswebapp'
    #azureSubscriptionSecundary: 'mss-vws-acc-cicd'
    #webAppNameSecundary: 'vwswebapp'
    #webEnvironment: 'Staging'
    # ============================================
    # parameters hieronder zijn voor acceptatie
    azureSubscriptionPrimary: 'mss-vws-primary-acc-cicd'
    webAppNamePrimary: 'vwspa-app-service'
    azureSubscriptionSecundary: 'mss-vws-secondary-acc-cicd'
    webAppNameSecundary: 'vwssa-app-service'
    webEnvironment: 'Staging'
    # ============================================
    projectName: '$(System.DefaultWorkingDirectory)/CdnDataReceiver2/CdnDataReceiver2.csproj'
