trigger:
- productie

resources:
  repositories:
    - repository: templates
      type: git
      name: MSS-Azure
      ref: master

extends:
  template: MSS-Azure-CoronaMelder-Pipelines/webapp-build-deploy.yml@templates
  parameters:
    environment: 'covid19-azure-production'
    # ============================================
    # parameters hieronder zijn alleen voor testen
    #azureSubscriptionPrimary: 'mss-vws-acc-cicd'
    #webAppNamePrimary: 'vwswebapp'
    #azureSubscriptionSecundary: 'mss-vws-acc-cicd'
    #webAppNameSecundary: 'vwswebapp'
    #webEnvironment: 'Production'
    # ============================================
    # parameters hieronder zijn voor productie
    azureSubscriptionPrimary: 'mss-vws-primary-prd-cicd'
    webAppNamePrimary: 'vwspp-app-service'
    azureSubscriptionSecundary: 'mss-vws-secondary-prd-cicd'
    webAppNameSecundary: 'vwssp-app-service'
    webEnvironment: 'Production'
    # ============================================
    projectName: '$(System.DefaultWorkingDirectory)/ExposureNotification.Backend.CdnDataReceiver.sln'
