trigger:
- productie

resources:
  repositories:
    - repository: templates
      type: git
      name: MSS-Azure
      ref: master

extends:
  template: MSS-Azure-CoronaMelder-Pipelines/functionapp-build-deploy.yml@templates
  parameters:
    environment: 'covid19-azure-production'
    # ============================================
    # parameters hieronder zijn alleen voor testen
    #azureSubscriptionPrimary: 'mss-vws-acc-cicd'
    #functionAppNamePrimary: 'vwssync'
    #azureSubscriptionSecundary: 'mss-vws-acc-cicd'
    #functionAppNameSecundary: 'vwssync'
    #webEnvironment: 'Production'
    # ============================================
    # parameters hieronder zijn voor productie
    azureSubscriptionPrimary: 'mss-vws-primary-prd-cicd'
    functionAppNamePrimary: 'vwspp-function-app'
    azureSubscriptionSecundary: 'mss-vws-secondary-prd-cicd'
    functionAppNameSecundary: 'vwssp-function-app'
    webEnvironment: 'Production'
    # ============================================
    projectName: '$(System.DefaultWorkingDirectory)/ExposureNotification.Backend.CdnRegionSync.sln'
