version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
    links:
      - 'db_mssql:database'
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ./db:/var/data/project
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"