version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '5004:5000'
      - '5005:5001'
    links:
      - 'db_mssql:database'
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"
  db_icc_backend:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"
  db_icc_portal:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"